version: '3'
services:
  sbt:
    image: sbtscala/scala-sbt:eclipse-temurin-jammy-11.0.22_7_1.9.9_2.13.13
    container_name: sbt
    volumes:
        - .:/root
    ports:
        - 9000:9000
    expose:
        - "9000"
    tty: true
  db:
    image: mysql:8.3.0
    container_name: mysql
    environment:
        MYSQL_DATABASE: playdb
        MYSQL_USER: hoge
        MYSQL_PASSWORD: hogepassword
        MYSQL_ROOT_PASSWORD: hogepassword
    volumes:
        - ./db/data:/var/lib/mysql
        - ./db/sql:/docker-entrypoint-initdb.d
        - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
        - "3306:3306"
    expose:
        - "3306"
